from .do_not_back_model import DoNotBackModel
from .do_not_break_famous_fence_model import DoNotBreakFamousFenceModel
from .do_not_build_right_wall_model import DoNotBuildRightWallModel
from .do_not_build_wall_on_file_9_model import DoNotBuildWallOnFile9Model
from .do_not_depromotion_model import DoNotDepromotionModel
from .do_not_drop_piece_model import DoNotDropPieceModel
from .do_not_drop_rook_in_own_camp_model import DoNotDropRookInOwnCampModel
from .do_not_move_left_lance_model import DoNotMoveLeftLanceModel
from .do_not_move_right_lance_model import DoNotMoveRightLanceModel
from .do_not_move_rook_model import DoNotMoveRookModel
from .do_not_go_left_model import DoNotGoLeftModel
from .do_not_up_dog_and_cat_side_by_side_model import DoNotUpDogAndCatSideBySideModel
from .do_not_up_to_rank_6_model import DoNotUpToRank6Model
from .do_not_move_until_rook_moves_model import DoNotMoveUntilRookMovesModel
from .will_for_three_gold_and_silver_coins_to_gather_to_the_right_model import WillForThreeGoldAndSilverCoinsToGatherToTheRightModel
# 削除 from .will_not_to_be_cut_88_bishop import WillNotToBeCut88Bishop
from .will_not_to_move_37_pawn_model import WillNotToMove37PawnModel
from .will_swinging_rook_model import WillSwingingRookModel
# 削除 from .will_to_take_the_piece_without_losing_anything import WillToTakeThePieceWithoutLosingAnything
