[engine]
    name = "Dev Kifuuuuuuwarabe Beginning"


# デバッグ・モード
[debug_mode]
    search_do_undo = false  # 何だっけこれ？


# 探索関連
[search]
    # 思考時にランダム性が少しでも加わるか。
    #       遊ぶときや、研究を外す以外のときは、ランダム性は無くてもいいぐらい。
    there_is_randomness = true


# 号令
[gourei_commands]

    # 訓令［ゾウの頭を守れ］
    do_protect_bishop_head = true

    # 号令［相手が手を戻したら自分も戻せ］
    if_opponent_rollback_move_me_too = true

    # 号令［戻るな］
    do_not_back = true

    # 訓令［名の有る囲いを崩すな］
    do_not_break_famous_fence = true

    # 号令［右壁を作るな］
    do_not_build_right_wall = true

    # 号令［イヌとネコを横並びに上げるな］
    do_not_up_dog_and_cat_side_by_side = true

    # 号令［６段目に上がるな］
    do_not_up_to_rank_6 = true

    # 号令［キリンが動くまで動くな］
    do_not_move_until_rook_moves = true

    # 号令［左へ行くな］
    do_not_go_left = true

    # 号令［左のイノシシは動くな］
    do_not_move_left_lance = true

    # 号令［右のイノシシは動くな］
    do_not_move_right_lance = true

    # 号令［キリンは動くな］
    do_not_move_rook = true

    # 号令［成らないということをするな］
    do_not_depromotion = true

    # 号令［駒を打つな］
    do_not_drop_piece = true

    # 号令［自陣に飛車打つな］
    do_not_drop_rook_in_own_camp = false

    # 号令［９筋に壁を作るな］
    do_not_build_wall_on_file_9 = true

    # 号令［頭が丸い駒の頭のヒヨコを突くな］
    do_not_peck_at_chick_on_roundheaded_piece = true

    # 号令［犬を６段目に登らせるな］
    do_not_let_dog_climb_6_rank = true

    # 以下、古い実装
    # --------------

    # ［金銀３枚が右に集まる］意志
    will_for_three_gold_and_silver_coins_to_gather_to_the_right = false     #true

    # ［３七の歩を突かない］意志
    will_not_to_move_37_pawn = false    #true

    # ［振り飛車をする］意志
    will_swinging_rook = false      #true

    # 削除
    ## ［８八の角を素抜かれない］意志
    #will_not_to_be_cut_88_bishop = false        #true

    # 削除
    ## ［駒取って損しない］意志
    #will_to_take_the_piece_without_losing_anything = false      #true
