[engine]
    name = "Kifuuuuuuwarabe Beginning"

# 行進演算
[march_operations]

    # 行進［戻るな］
    do_not_back = true

    # 行進［右壁を作るな］
    do_not_build_right_wall = true

    # 行進［イヌを上げるな］
    do_not_up_the_dog = true

    # 行進［６段目に上がるな］
    do_not_up_to_rank_6 = true

    # 行進［キリンが動くまで動くな］
    do_not_move_until_rook_moves = true

    # 行進［左へ行くな］
    do_not_go_left = true

    # 行進［左のイノシシは動くな］
    do_not_move_left_lance = true

    # 行進［右のイノシシは動くな］
    do_not_move_right_lance = true

    # 行進［きりんは動くな］
    do_not_move_rook = true

    # ［金銀３枚が右に集まる］意志
    will_for_three_gold_and_silver_coins_to_gather_to_the_right = false     #true

    # ［３七の歩を突かない］意志
    will_not_to_move_37_pawn = false    #true

    # ［振り飛車をする］意志
    will_swinging_rook = false      #true

    # ［８八の角を素抜かれない］意志
    will_not_to_be_cut_88_bishop = false        #true

    # ［駒取って損しない］意志
    will_to_take_the_piece_without_losing_anything = false      #true
