[engine]
    name = "Kifuuuuuuwarabe Beginning"


# デバッグ・モード
[debug_mode]
    search_do_undo = true


# 探索関連
[search]
    # 取る手の読みの深さ。
    # 3 にすると十分機能する。奇数の方がよい？
    # 7 にすると、だんだんと思考時間が長くなって、そのうち止まってしまう？
    # 511 で実質無制限だが止まってしまう。不具合があるのかも。
    capture_depth = 2 #7 #511

    # 思考時にランダム性が少しでも加わるか。
    #       遊ぶときや、研究を外す以外のときは、ランダム性は無くてもいいぐらい。
    there_is_randomness = true


# 行進演算
[march_operations]

    # 行進［戻るな］
    do_not_back = true

    # 行進［名の有る囲いを崩すな］
    do_not_break_famous_fence = true

    # 行進［右壁を作るな］
    do_not_build_right_wall = true

    # 行進［イヌとネコを横並びに上げるな］
    do_not_up_dog_and_cat_side_by_side = true

    # 行進［６段目に上がるな］
    do_not_up_to_rank_6 = true

    # 行進［キリンが動くまで動くな］
    do_not_move_until_rook_moves = true

    # 行進［左へ行くな］
    do_not_go_left = true

    # 行進［左のイノシシは動くな］
    do_not_move_left_lance = true

    # 行進［右のイノシシは動くな］
    do_not_move_right_lance = true

    # 行進［キリンは動くな］
    do_not_move_rook = true

    # ［金銀３枚が右に集まる］意志
    will_for_three_gold_and_silver_coins_to_gather_to_the_right = false     #true

    # ［３七の歩を突かない］意志
    will_not_to_move_37_pawn = false    #true

    # ［振り飛車をする］意志
    will_swinging_rook = false      #true

    # 削除
    ## ［８八の角を素抜かれない］意志
    #will_not_to_be_cut_88_bishop = false        #true

    # 削除
    ## ［駒取って損しない］意志
    #will_to_take_the_piece_without_losing_anything = false      #true
