from .do_not_back import DoNotBack
from .do_not_break_famous_fence import DoNotBreakFamousFence
from .do_not_build_right_wall import DoNotBuildRightWall
from .do_not_move_left_lance import DoNotMoveLeftLance
from .do_not_move_right_lance import DoNotMoveRightLance
from .do_not_move_rook import DoNotMoveRook
from .do_not_go_left import DoNotGoLeft
from .do_not_up_dog_and_cat_side_by_side import DoNotDogAndCatSideBySide
from .do_not_up_to_rank_6 import DoNotUpToRank6
from .do_not_move_until_rook_moves import DoNotMoveUntilRookMoves
from .will_for_three_gold_and_silver_coins_to_gather_to_the_right import WillForThreeGoldAndSilverCoinsToGatherToTheRight
# 削除 from .will_not_to_be_cut_88_bishop import WillNotToBeCut88Bishop
from .will_not_to_move_37_pawn import WillNotToMove37Pawn
from .will_swinging_rook import WillSwingingRook
# 削除 from .will_to_take_the_piece_without_losing_anything import WillToTakeThePieceWithoutLosingAnything
